name: express_partner
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async:
  badges: ^2.0.1
  bubble_tab_indicator: ^0.1.6
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.3
  firebase_storage: ^10.0.3
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  date_time_picker: ^2.1.0
  dio: ^4.0.0
  dotted_line: ^3.0.0
  dropdown_search: ^1.0.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  fl_chart: ^0.40.0
  flutter_local_notifications: ^8.2.0
  flutter_modular: ^4.0.1+2
  flutter_native_splash: ^1.2.4
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.10
  google_maps_flutter_web: ^0.3.1
  grouped_list: ^4.1.0
  http: ^0.13.3
  location: ^4.3.0
  mime: ^1.0.0
  multi_select_flutter: ^4.0.0
  permission_handler: ^8.1.6
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  syncfusion_flutter_datepicker: ^19.2.62
  timelines: ^0.1.0
  url_launcher: ^6.0.12
  whatsapp_unilink: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_automation: ^2.0.0
  get: ^4.3.8
  geoflutterfire: ^3.0.1
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
